# -*- coding: utf-8 -*-
"""3097 Defaulter 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BpdlBVW4Sti0jL8QHOWkJd2b8AShu1ML
"""

!pip install pandas
!pip install scikit-learn
!pip install matplotlib
!pip install seaborn
!pip install xgboost

from google.colab import files
uploaded = files.upload()

import pandas as pd

data = pd.read_csv('/content/traffic.csv')
print(data.head())

# Strip spaces and lowercase all column names
data.columns = [c.strip().lower() for c in data.columns]
print(data.columns)

print(data.head())

print(data['datetime'].head())