# -*- coding: utf-8 -*-
"""3097_defaulter_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X8fsDue-4dQPeB83lrhCKe9DeoMI0QYW
"""

from google.colab import files
files.upload()

import pandas as pd
df = pd.read_csv('/content/pesticides.csv')
df.head()

df = df.dropna()   # remove rows with missing values (simple approach)

df.columns

X = df.drop('Area', axis=1)  # everything except the output
y = df['Area']               # the output column

df.dtypes

# Convert text columns into numeric form (0s and 1s)
df = pd.get_dummies(df, drop_first=True)

X = df.drop('Value', axis=1)  # everything except Value
y = df['Value']               # what we want to predict

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(random_state=42)
model.fit(X_train, y_train)

from sklearn.metrics import mean_squared_error
import numpy as np

r2 = r2_score(y_test, preds)
rmse = np.sqrt(mean_squared_error(y_test, preds))

print(f"Model Accuracy (R²): {r2:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")

!pip install --upgrade scikit-learn