# -*- coding: utf-8 -*-
"""3097 defaulter 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PrNnulkl2FEpaRbkU8dCPSMwx1OqUxAI
"""

!pip install tensorflow
!pip install pandas
!pip install scikit-learn
!pip install matplotlib
!pip install opencv-python

import pandas as pd

# Load CSV file
data = pd.read_csv('/content/breast-cancer.csv')
print(data.head())

import pandas as pd

data = pd.read_csv('/content/breast-cancer.csv')
print(data.columns)

# Strip spaces and lowercase all column names
data.columns = [c.strip().lower() for c in data.columns]
print(data.columns)

print(data.head())