# -*- coding: utf-8 -*-
"""untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/saikeertana1802/64d256e3ddb30b98e35095821b6e5cc5/untitled4.ipynb
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

file_path = "/content/Weather and Enegry data.xlsx"
sheet_name = 0

df = pd.read_excel(file_path, sheet_name=sheet_name)
print("✅ Data Loaded Successfully")
print(df.head())

df = df.iloc[1:]



X = df[['Unnamed: 8', 'Unnamed: 9']]
y = df['Unnamed: 7']

y = (y > y.median()).astype(int)

# ---------- Step 4: Split data ----------
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# ---------- Step 5: Logistic Regression ----------
log_model = LogisticRegression()
log_model.fit(X_train, y_train)
y_pred_log = log_model.predict(X_test)

print("\n🔹 Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_log))

# ---------- Step 6: Decision Tree ----------
tree_model = DecisionTreeClassifier()
tree_model.fit(X_train, y_train)
y_pred_tree = tree_model.predict(X_test)

print("🔹 Decision Tree Accuracy:", accuracy_score(y_test, y_pred_tree))

print(df.columns)