# -*- coding: utf-8 -*-
"""svr_cropyieldprediction_3109.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SYLkJevr2b5qX5zThzt0aAIx-XoAoS8v
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error
import numpy as np
import matplotlib.pyplot as plt

# Load dataset
df = pd.read_csv("/content/drive/MyDrive/SEM VII/DS Defaulters/crop_yield_dataset.csv")

X = df.drop(columns=["Yield"])
y = df["Yield"]

# Split dataset into training and testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Create SVR model
svr = SVR(kernel="rbf", C=100, epsilon=0.1)
svr.fit(X_train, y_train)

# Predict
svr_preds = svr.predict(X_test)

# Calculate RMSE
svr_rmse = np.sqrt(mean_squared_error(y_test, svr_preds))
print(f"SVR RMSE: {svr_rmse}")

# Plot Actual vs Predicted
plt.scatter(y_test, svr_preds)
plt.xlabel("Actual Yield")
plt.ylabel("Predicted Yield")
plt.title("Crop Yield Prediction using SVR")
plt.show()