# -*- coding: utf-8 -*-
"""svm

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ew2wBHBDsuwu5CUeSEzVS1-wwox3-4sy
"""

import numpy as np
from sklearn.svm import SVC

X = np.array([[1, 2], [2, 3], [3, 3], [2, 1], [3, 2], [4, 1]])
y = np.array([0, 0, 0, 1, 1, 1])

model = SVC(kernel='linear', C=1)

model.fit(X, y)

new_data = np.array([[2.5, 2.5]])
prediction = model.predict(new_data)

print(f"Features: {X}")
print(f"Labels: {y}")
print(f"Prediction for {new_data[0]}: {prediction[0]}")